server:
  port: 8888
  servlet:
    context-path: /book_manager
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.96.178.201:3306/book_manager?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
  resources:
    static-locations: "classpath:templates/,classpath:static/"
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

mybatis:
  mapper-locations: "classpath:/mapper/*.xml"
  type-aliases-package: com.sl.book_manager.persist.entity

